#!/usr/bin/env bash
# scripts/pr-comment-bot.sh · Generate as-built PR summary
set -euo pipefail

cat <<EOF
## 🤖 As-built Summary

**Commit**: \`${GITHUB_SHA:0:7}\`
**Branch**: ${GITHUB_HEAD_REF:-main}
**Actor**: @${GITHUB_ACTOR:-unknown}

### Gate Status
| Gate | Status |
|---|---|
| G1 · Build       | $(cat as-built/g1-result.json 2>/dev/null | jq -r .status || echo "N/A") |
| G2 · Safety      | $(cat as-built/g2-result.json 2>/dev/null | jq -r .status || echo "N/A") |
| G3 · Health      | $(cat as-built/g3-result.json 2>/dev/null | jq -r .status || echo "N/A") |
| G4 · Eval        | $(cat as-built/g4-result.json 2>/dev/null | jq -r .status || echo "N/A") |

### Ledger
Last entry: $(tail -1 as-built/ledger.jsonl 2>/dev/null || echo "no entries yet")

---
*Auto-generated by \`pr-comment-bot.yml\` · upsert mode*
EOF
